import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import AOSInitializer from "@/components/AOSInitializer";

const outfit = Outfit({
  subsets: ['latin'],
  weight: ['400', '600', '700'], // Adjust as needed
  display: 'swap',
});


export const metadata: Metadata = {
  title: "Illovo Nursery",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={outfit.className}
        suppressHydrationWarning
      >
        <AOSInitializer />
        {children}
      </body>
    </html>
  );
}
